name: Code Quality
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - name: Installing node ${{matrix.node}}
        run: npm ci
      - name: Running test
        run: npm run lint

  style:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - name: Installing node ${{matrix.node}}
        run: npm ci
      - name: Checking style with prettier
        run: npm run format:check

  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node: [16]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - name: Installing node ${{matrix.node}}
        run: npm ci
      - name: Running test
        run: npm t
